"""add category, skills and brief fields to scenarios

Revision ID: 3640d8280d17
Revises: fd75fd1e5a21
Create Date: 2026-10-09 12:28:51.666711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3640d8280d17'
down_revision: Union[str, Sequence[str], None] = 'fd75fd1e5a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('scenarios', sa.Column('skills', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('scenarios', sa.Column('estimated_minutes', sa.Integer(), server_default=sa.text('10'), nullable=False))
    op.add_column('scenarios', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('scenarios', sa.Column('customer_personality', sa.String(length=255), nullable=True))
    op.add_column('scenarios', sa.Column('customer_emotion', sa.String(length=255), nullable=True))
    op.add_column('scenarios', sa.Column('customer_background', sa.Text(), nullable=True))
    op.add_column('scenarios', sa.Column('situation', sa.Text(), nullable=True))
    op.add_column('scenarios', sa.Column('customer_goal', sa.Text(), nullable=True))
    op.add_column('scenarios', sa.Column('trainee_objective', sa.Text(), nullable=True))
    op.add_column('scenarios', sa.Column('important_information', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('scenarios', sa.Column('escalation_behavior', sa.Text(), nullable=True))
    op.add_column('scenarios', sa.Column('success_criteria', sa.Text(), nullable=True))
    op.create_index(op.f('ix_scenarios_category'), 'scenarios', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_category'), table_name='scenarios')
    op.drop_column('scenarios', 'success_criteria')
    op.drop_column('scenarios', 'escalation_behavior')
    op.drop_column('scenarios', 'important_information')
    op.drop_column('scenarios', 'trainee_objective')
    op.drop_column('scenarios', 'customer_goal')
    op.drop_column('scenarios', 'situation')
    op.drop_column('scenarios', 'customer_background')
    op.drop_column('scenarios', 'customer_emotion')
    op.drop_column('scenarios', 'customer_personality')
    op.drop_column('scenarios', 'customer_name')
    op.drop_column('scenarios', 'estimated_minutes')
    op.drop_column('scenarios', 'skills')
    op.drop_column('scenarios', 'category')
    # ### end Alembic commands ###
