"""move id, created, updated field to base model

Revision ID: 4a972bb9a0ef
Revises: 10ae95a9aeb4
Create Date: 2026-03-11 11:19:02.849459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a972bb9a0ef'
down_revision: Union[str, Sequence[str], None] = '10ae95a9aeb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimension_scores', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('dimension_scores', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_dimension_scores_id'), table_name='dimension_scores')
    op.create_index(op.f('ix_dimension_scores_id'), 'dimension_scores', ['id'], unique=True)
    op.add_column('red_flags', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('red_flags', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_red_flags_id'), table_name='red_flags')
    op.create_index(op.f('ix_red_flags_id'), 'red_flags', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_red_flags_id'), table_name='red_flags')
    op.create_index(op.f('ix_red_flags_id'), 'red_flags', ['id'], unique=False)
    op.drop_column('red_flags', 'updated_at')
    op.drop_column('red_flags', 'created_at')
    op.drop_index(op.f('ix_dimension_scores_id'), table_name='dimension_scores')
    op.create_index(op.f('ix_dimension_scores_id'), 'dimension_scores', ['id'], unique=False)
    op.drop_column('dimension_scores', 'updated_at')
    op.drop_column('dimension_scores', 'created_at')
    # ### end Alembic commands ###
