"""add_system_prompt_to_scenarios

Revision ID: 62164ee26966
Revises: 4bff770056e0
Create Date: 2026-03-10 09:40:34.941656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62164ee26966'
down_revision: Union[str, Sequence[str], None] = '4bff770056e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'system_prompt')
    # ### end Alembic commands ###
