"""add trainee onboarding fields to users

Revision ID: fd75fd1e5a21
Revises: 8bdf403a9283
Create Date: 2026-10-09 11:37:05.925020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd75fd1e5a21'
down_revision: Union[str, Sequence[str], None] = '8bdf403a9283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('invite_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'invite_sent_at')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
